name: crave-DOVER-less
num_epochs: 10
l_num_epochs: 15
warmup_epochs: 2.5
ema: True
save_model: true
batch_size: 8
num_workers: 6
split_seed: 10

wandb:
    project_name: crave-DOVER-wo-less
data:
    videoQA:
        type: ViewDecompositionDataset
        args:
            weight: 0.598
            phase: train
            anno_file: /code/vqa/dover/crave-db/new_prompt.txt
            data_prefix: /code/vqa/dover/crave-db/
            sample_types:
                technical:
                    fragments_h: 7
                    fragments_w: 7
                    fsize_h: 32
                    fsize_w: 32
                    aligned: 32
                    clip_len: 32
                    frame_interval: 1
                    num_clips: 1
                aesthetic:
                    size_h: 224
                    size_w: 224
                    clip_len: 32
                    frame_interval: 1
                    t_frag: 32
                    num_clips: 1





model:
    type: DOVER
    args:
        backbone:
            technical:
                type: swin_tiny_grpb
                checkpoint: true
                pretrained:
            aesthetic:
                type: conv_tiny
        backbone_preserve_keys: technical,aesthetic
        divide_head: true
        vqa_head:
            in_channels: 768
            hidden_channels: 64
            
optimizer:
    lr: !!float 1e-3
    backbone_lr_mult: !!float 1e-1
    wd: 0.05
        
test_load_path: ./pretrained_weights/crave-DOVER-less_head_videoQA_0_eval_s_finetuned.pth

    
        
